# Generated by Django 4.2.2 on 2023-06-20 10:47

import companies.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to=companies.services.upload_logo_path)),
                ('person_category', models.CharField(choices=[('', 'None'), ('all', 'All'), ('ma', 'Male'), ('fe', 'Female'), ('ba', 'Baby')], default='all', max_length=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('director', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('phone1', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='\n        Telefon raqam: 13 ta belgidan iborat bolishi kerak. P.s: +998912345678\n    ', regex='^[+]998\\d{9}$')])),
                ('phone2', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='\n        Telefon raqam: 13 ta belgidan iborat bolishi kerak. P.s: +998912345678\n    ', regex='^[+]998\\d{9}$')])),
                ('logo', models.ImageField(upload_to=companies.services.upload_logo_path)),
                ('address', models.CharField(max_length=150)),
                ('google_map', models.URLField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('person_category', models.CharField(choices=[('', 'None'), ('all', 'All'), ('ma', 'Male'), ('fe', 'Female'), ('ba', 'Baby')], default='', max_length=3)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.companybranch')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=companies.services.upload_serv_image_path)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companies.companyservice')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='companies.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='companies.companybranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
