# Generated by Django 4.2.2 on 2023-06-21 12:31

import companies.services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to=companies.services.upload_logo_path)),
                ('person_category', models.CharField(choices=[('', 'None'), ('all', 'All'), ('ma', 'Male'), ('fe', 'Female'), ('ba', 'Baby')], default='all', max_length=3)),
                ('status', models.CharField(blank=True, choices=[('ac', 'Active'), ('wt', 'Waiting'), ('rc', 'Recived'), ('rj', 'Rejected')], default='wt', max_length=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
