# Generated by Django 4.2.2 on 2023-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('wt', 'Waiting'), ('na', 'Not Active'), ('ar', 'Archive')], default='wt', max_length=3),
        ),
    ]
